# Generated by Django 4.2.4 on 2023-08-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('Bid', models.IntegerField(primary_key=True, serialize=False)),
                ('Bname', models.CharField(max_length=100)),
                ('Did', models.IntegerField()),
            ],
            options={
                'db_table': 'branchtable',
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('Did', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'districttable',
            },
        ),
    ]
